export enum LookupCategory {
  BLOOD_TYPE = 'BLOOD_TYPE',
  LIFESTYLE_HABITS = 'LIFESTYLE_HABITS',
  CHRONIC_CONDITIONS = 'CHRONIC_CONDITIONS',
  DISABILITY_TYPES = 'DISABILITY_TYPES',
  ALLERGY = 'ALLERGY',
  COMMON_SURGERIES = 'COMMON_SURGERIES',
}
